steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/autoremind:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/autoremind:latest', '.']
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autoremind:$SHORT_SHA']
    id: 'push-image-versioned'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autoremind:latest']
    id: 'push-image-latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-web-server'
    args:
      - gcloud
      - run
      - deploy
      - autoremind
      - --image=gcr.io/$PROJECT_ID/autoremind:$SHORT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --set-env-vars=FIREBASE_SERVICE_ACCOUNT_PATH=/app/services/config/firebase_service_account.json
      - >-
        --set-secrets=FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID:latest,FIREBASE_API_KEY=FIREBASE_API_KEY:latest,FIREBASE_AUTH_DOMAIN=FIREBASE_AUTH_DOMAIN:latest,FIREBASE_SERVICE_ACCOUNT_JSON=FIREBASE_SERVICE_ACCOUNT_JSON:latest,/secrets/oauth/oauth_client_secret.json=oauth_client_secret:latest,/secrets/firebase_sa/firebase_service_account.json=firebase_service_account:latest,/secrets/gmail/token.json=gmail_token:latest
      - --project=$PROJECT_ID
      - --quiet

images:
  - 'gcr.io/$PROJECT_ID/autoremind:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/autoremind:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

