"""
Upload assignment resources to Firestore.

Uploads each row to the 'assignment_resources' collection using a stable
document ID derived from (course_code, assignment_code, resource_name) so
re-running always updates existing entries (e.g. assignment_name renames)
rather than silently skipping them.

Also deletes stale CS61A docs whose IDs are no longer generated by this script,
keeping Firestore in sync with the RESOURCES list below.
"""

import re
import sys
from pathlib import Path
from typing import Dict, List, Set

import firebase_admin
from firebase_admin import credentials, firestore

SERVICES_DIR = Path(__file__).resolve().parent.parent
if str(SERVICES_DIR) not in sys.path:
    sys.path.append(str(SERVICES_DIR))

from shared import settings


def init_firestore() -> firestore.Client:
    """Initialize Firebase Admin SDK and return a Firestore client."""
    if not firebase_admin._apps:
        sa_path = str(settings.FIREBASE_SERVICE_ACCOUNT_PATH)
        cred = credentials.Certificate(sa_path)
        firebase_admin.initialize_app(cred, {
            "projectId": settings.FIREBASE_PROJECT_ID,
        })
    return firestore.client()


# Fields: (course_code, assignment_code, assignment_name, resource_type, resource_name, link)
#
# assignment_code and assignment_name must exactly match the Gradescope assignment name.
# These names drive both the deadline matching (submission check) and the resource lookup.
RESOURCES = [
    # ── CS61A Labs ──────────────────────────────────────────────────────────
    ("CS61A", "Lab 0", "Lab 0", "Reading", "Ch 1.1: Getting Started", "https://www.composingprograms.com/pages/11-getting-started.html"),

    ("CS61A", "Lab 1", "Lab 1", "Reading", "Ch 1.2: Elements of Programming", "https://www.composingprograms.com/pages/12-elements-of-programming.html"),
    ("CS61A", "Lab 1", "Lab 1", "Reading", "Ch 1.3: Defining New Functions", "https://www.composingprograms.com/pages/13-defining-new-functions.html"),
    ("CS61A", "Lab 1", "Lab 1", "Reading", "Ch 1.4: Designing Functions", "https://www.composingprograms.com/pages/14-designing-functions.html"),
    ("CS61A", "Lab 1", "Lab 1", "Reading", "Ch 1.5: Control", "https://www.composingprograms.com/pages/15-control.html"),
    ("CS61A", "Lab 1", "Lab 1", "Video", "Lecture 1: Welcome, Functions, Exceptions", "https://www.youtube.com/watch?v=gNv81_4X0uU&list=PL6BsET-8jgYULSxiV2garZ0FxbnXR08MP&index=1"),
    ("CS61A", "Lab 1", "Lab 1", "Video", "Lecture 2: Control", "https://www.youtube.com/watch?v=IPec2A7j2bY&list=PL6BsET-8jgYVCz97Y75GRXSWbb4sTpDIR"),

    ("CS61A", "Lab 2", "Lab 2", "Reading", "Ch 1.6: Higher-Order Functions", "https://www.composingprograms.com/pages/16-higher-order-functions.html"),
    ("CS61A", "Lab 2", "Lab 2", "Video", "Lecture 3: Higher-Order Functions", "https://www.youtube.com/watch?v=pveIuZT0GJE&list=PL6BsET-8jgYXvcnnEX7x2_USaYug9xZFv"),
    ("CS61A", "Lab 2", "Lab 2", "Video", "Lecture 4: Environments", "https://www.youtube.com/watch?v=1P2UgdAWwYg&list=PLx38hZJ5RLZfuSmYOTG7sKY44pEC01398&index=1"),

    ("CS61A", "Lab 3", "Lab 3", "Reading", "Ch 1.7: Recursive Functions", "https://www.composingprograms.com/pages/17-recursive-functions.html"),
    ("CS61A", "Lab 3", "Lab 3", "Video", "Lecture 5: Recursion", "https://www.youtube.com/watch?v=31EDjrN1x5k&list=PL6BsET-8jgYUUBHIgUAqjrMUoPCGQcYdl"),
    ("CS61A", "Lab 3", "Lab 3", "Video", "Lecture 6: Tree Recursion", "https://www.youtube.com/watch?v=VYYkJ1OLXBw&list=PL6BsET-8jgYUUWPap4etQjZVWlWUeFxn0"),

    ("CS61A", "Lab 4", "Lab 4", "Reading", "Ch 2.3: Sequences", "https://www.composingprograms.com/pages/23-sequences.html"),
    ("CS61A", "Lab 4", "Lab 4", "Video", "Lecture 7: Sequences and Containers", "https://www.youtube.com/watch?v=-Q45UcQ2XJk&list=PLx38hZJ5RLZc8KP9bVLM1C90HprD0ctrq&index=1"),
    ("CS61A", "Lab 4", "Lab 4", "Video", "Lecture 9: Trees", "https://www.youtube.com/watch?v=qFCJANh5ht8&list=PLEd2rgVCX-1M"),

    ("CS61A", "Lab 5", "Lab 5", "Reading", "Ch 2.4: Mutable Data", "https://www.composingprograms.com/pages/24-mutable-data.html"),
    ("CS61A", "Lab 5", "Lab 5", "Reading", "Ch 2.2: Data Abstraction", "https://www.composingprograms.com/pages/22-data-abstraction.html"),
    ("CS61A", "Lab 5", "Lab 5", "Reading", "Ch 4.2: Implicit Sequences", "https://www.composingprograms.com/pages/42-implicit-sequences.html"),
    ("CS61A", "Lab 5", "Lab 5", "Video", "Lecture 8: Mutability and Data Abstraction", "https://www.youtube.com/watch?v=Q-CewobDFZM&list=PLWelSnn5Gemc"),
    ("CS61A", "Lab 5", "Lab 5", "Video", "Lecture 10: Iterators and Generators", "https://www.youtube.com/watch?v=On-kFyFp8HY&list=PLx38hZJ5RLZdEOl-AAfpul_-iySZzI4C3&index=1"),

    ("CS61A", "Lab 6", "Lab 6", "Reading", "Ch 2.5: Object-Oriented Programming", "https://www.composingprograms.com/pages/25-object-oriented-programming.html"),
    ("CS61A", "Lab 6", "Lab 6", "Reading", "Ch 2.7: Object Abstraction", "https://www.composingprograms.com/pages/27-object-abstraction.html"),
    ("CS61A", "Lab 6", "Lab 6", "Video", "Lecture 13: Objects and Attributes", "https://www.youtube.com/watch?v=XdRZkeCRXs4&list=PLx38hZJ5RLZcLC84b96V3_gkgu0L-pP8H&index=1"),
    ("CS61A", "Lab 6", "Lab 6", "Video", "Lecture 14: Inheritance and String Representation", "https://www.youtube.com/watch?v=Bqpe1iyq5vE&list=PLx38hZJ5RLZeBJZPjGNKBdMJVczwYXHlR&index=1"),

    ("CS61A", "Lab 7", "Lab 7", "Reading", "Ch 2.7: Object Abstraction", "https://www.composingprograms.com/pages/27-object-abstraction.html"),
    ("CS61A", "Lab 7", "Lab 7", "Reading", "Ch 2.9: Recursive Objects", "https://www.composingprograms.com/pages/29-recursive-objects.html"),
    ("CS61A", "Lab 7", "Lab 7", "Video", "Lecture 14: Inheritance and String Representation", "https://www.youtube.com/watch?v=Bqpe1iyq5vE&list=PLx38hZJ5RLZeBJZPjGNKBdMJVczwYXHlR&index=1"),
    ("CS61A", "Lab 7", "Lab 7", "Video", "Lecture 15: Mutable Trees", "https://www.youtube.com/watch?v=vg9tCzw2hPc&list=PLx38hZJ5RLZc2kUmt4l-3C3yFTA1zRQW7&index=1"),

    ("CS61A", "Lab 8", "Lab 8", "Reading", "Ch 2.9: Recursive Objects", "https://www.composingprograms.com/pages/29-recursive-objects.html"),
    ("CS61A", "Lab 8", "Lab 8", "Video", "Lecture 16: Linked Lists", "https://www.youtube.com/watch?v=yC4WPw_6ehY&list=PLx38hZJ5RLZfpHYLasG2fsMHBFDWvdkBT&index=1"),

    ("CS61A", "Lab 9", "Lab 9", "Reading", "Ch 3.1: Scheme Introduction", "https://www.composingprograms.com/pages/31-introduction.html"),
    ("CS61A", "Lab 9", "Lab 9", "Reading", "Ch 3.2: Functional Programming", "https://www.composingprograms.com/pages/32-functional-programming.html"),
    ("CS61A", "Lab 9", "Lab 9", "Video", "Lecture 18: Scheme", "https://www.youtube.com/watch?v=esIvijecRFw&list=PL6BsET-8jgYWGDX7c-OKSMCh4QCBZ7Bs4"),
    ("CS61A", "Lab 9", "Lab 9", "Video", "Lecture 19: Scheme Lists", "https://www.youtube.com/watch?v=M8nvWOAHLso&list=PL6BsET-8jgYW3h5HuWwcoTP4NTmLGB95p"),

    ("CS61A", "Lab 10", "Lab 10", "Reading", "Ch 3.4: Interpreters (Combination)", "https://www.composingprograms.com/pages/34-interpreters-for-languages-with-combination.html"),
    ("CS61A", "Lab 10", "Lab 10", "Reading", "Ch 3.5: Interpreters (Abstraction)", "https://www.composingprograms.com/pages/35-interpreters-for-languages-with-abstraction.html"),
    ("CS61A", "Lab 10", "Lab 10", "Video", "Lecture 20: Interpreters", "https://www.youtube.com/watch?v=bnUkFcTcUxM&list=PLx38hZJ5RLZeeyD43PD6M-wNmMg88IZXW&index=1"),
    ("CS61A", "Lab 10", "Lab 10", "Video", "Lecture 21: Tail Calls", "https://www.youtube.com/watch?v=zOxxB-gdO9U&list=PLx38hZJ5RLZdTRcbg-7Y59QARgHW4i3E8&index=1"),

    ("CS61A", "Lab 11", "Lab 11", "Reading", "Ch 4.3: Declarative Programming", "https://www.composingprograms.com/pages/43-declarative-programming.html"),
    ("CS61A", "Lab 11", "Lab 11", "Video", "Lecture 22: SQL and Tables", "https://www.youtube.com/watch?v=lombSNkvRR4&list=PLx38hZJ5RLZesH9b4St6HNAH-NC0yOD00&index=1"),
    ("CS61A", "Lab 11", "Lab 11", "Video", "Lecture 23: Aggregation and Databases", "https://www.youtube.com/watch?v=2ajhv_e_u5Q&list=PLx38hZJ5RLZeSZJObFKl1993Q5cXMABL3&index=1"),

    ("CS61A", "Lab 12", "Lab 12", "Video", "Lecture 27: Final Review", "https://www.youtube.com/watch?v=_wfbb189nJA&list=PLx38hZJ5RLZf1a2bhgcoj_1Ifkn8tli0L&index=1"),

    # ── CS61A Homework ──────────────────────────────────────────────────────
    ("CS61A", "Homework 1", "Homework 1", "Reading", "Ch 1.2: Elements of Programming", "https://www.composingprograms.com/pages/12-elements-of-programming.html"),
    ("CS61A", "Homework 1", "Homework 1", "Reading", "Ch 1.3: Defining New Functions", "https://www.composingprograms.com/pages/13-defining-new-functions.html"),
    ("CS61A", "Homework 1", "Homework 1", "Reading", "Ch 1.4: Designing Functions", "https://www.composingprograms.com/pages/14-designing-functions.html"),
    ("CS61A", "Homework 1", "Homework 1", "Reading", "Ch 1.5: Control", "https://www.composingprograms.com/pages/15-control.html"),
    ("CS61A", "Homework 1", "Homework 1", "Reading", "Ch 1.6: Higher-Order Functions", "https://www.composingprograms.com/pages/16-higher-order-functions.html"),
    ("CS61A", "Homework 1", "Homework 1", "Video", "Lecture 1: Welcome, Functions, Exceptions", "https://www.youtube.com/watch?v=gNv81_4X0uU&list=PL6BsET-8jgYULSxiV2garZ0FxbnXR08MP&index=1"),
    ("CS61A", "Homework 1", "Homework 1", "Video", "Lecture 2: Control", "https://www.youtube.com/watch?v=IPec2A7j2bY&list=PL6BsET-8jgYVCz97Y75GRXSWbb4sTpDIR"),
    ("CS61A", "Homework 1", "Homework 1", "Video", "Lecture 3: Higher-Order Functions", "https://www.youtube.com/watch?v=pveIuZT0GJE&list=PL6BsET-8jgYXvcnnEX7x2_USaYug9xZFv"),

    ("CS61A", "Homework 2", "Homework 2", "Reading", "Ch 1.7: Recursive Functions", "https://www.composingprograms.com/pages/17-recursive-functions.html"),
    ("CS61A", "Homework 2", "Homework 2", "Reading", "Ch 2.3: Sequences", "https://www.composingprograms.com/pages/23-sequences.html"),
    ("CS61A", "Homework 2", "Homework 2", "Video", "Lecture 5: Recursion", "https://www.youtube.com/watch?v=31EDjrN1x5k&list=PL6BsET-8jgYUUBHIgUAqjrMUoPCGQcYdl"),
    ("CS61A", "Homework 2", "Homework 2", "Video", "Lecture 6: Tree Recursion", "https://www.youtube.com/watch?v=VYYkJ1OLXBw&list=PL6BsET-8jgYUUWPap4etQjZVWlWUeFxn0"),
    ("CS61A", "Homework 2", "Homework 2", "Video", "Lecture 7: Sequences and Containers", "https://www.youtube.com/watch?v=-Q45UcQ2XJk&list=PLx38hZJ5RLZc8KP9bVLM1C90HprD0ctrq&index=1"),

    ("CS61A", "Homework 3", "Homework 3", "Reading", "Ch 2.4: Mutable Data", "https://www.composingprograms.com/pages/24-mutable-data.html"),
    ("CS61A", "Homework 3", "Homework 3", "Reading", "Ch 2.2: Data Abstraction", "https://www.composingprograms.com/pages/22-data-abstraction.html"),
    ("CS61A", "Homework 3", "Homework 3", "Reading", "Ch 2.3: Sequences", "https://www.composingprograms.com/pages/23-sequences.html"),
    ("CS61A", "Homework 3", "Homework 3", "Reading", "Ch 4.2: Implicit Sequences", "https://www.composingprograms.com/pages/42-implicit-sequences.html"),
    ("CS61A", "Homework 3", "Homework 3", "Video", "Lecture 8: Mutability and Data Abstraction", "https://www.youtube.com/watch?v=Q-CewobDFZM&list=PLWelSnn5Gemc"),
    ("CS61A", "Homework 3", "Homework 3", "Video", "Lecture 9: Trees", "https://www.youtube.com/watch?v=qFCJANh5ht8&list=PLEd2rgVCX-1M"),
    ("CS61A", "Homework 3", "Homework 3", "Video", "Lecture 10: Iterators and Generators", "https://www.youtube.com/watch?v=On-kFyFp8HY&list=PLx38hZJ5RLZdEOl-AAfpul_-iySZzI4C3&index=1"),

    ("CS61A", "Homework 4", "Homework 4", "Reading", "Ch 2.5: Object-Oriented Programming", "https://www.composingprograms.com/pages/25-object-oriented-programming.html"),
    ("CS61A", "Homework 4", "Homework 4", "Reading", "Ch 2.7: Object Abstraction", "https://www.composingprograms.com/pages/27-object-abstraction.html"),
    ("CS61A", "Homework 4", "Homework 4", "Reading", "Ch 2.9: Recursive Objects", "https://www.composingprograms.com/pages/29-recursive-objects.html"),
    ("CS61A", "Homework 4", "Homework 4", "Video", "Lecture 13: Objects and Attributes", "https://www.youtube.com/watch?v=XdRZkeCRXs4&list=PLx38hZJ5RLZcLC84b96V3_gkgu0L-pP8H&index=1"),
    ("CS61A", "Homework 4", "Homework 4", "Video", "Lecture 14: Inheritance and String Representation", "https://www.youtube.com/watch?v=Bqpe1iyq5vE&list=PLx38hZJ5RLZeBJZPjGNKBdMJVczwYXHlR&index=1"),
    ("CS61A", "Homework 4", "Homework 4", "Video", "Lecture 15: Mutable Trees", "https://www.youtube.com/watch?v=vg9tCzw2hPc&list=PLx38hZJ5RLZc2kUmt4l-3C3yFTA1zRQW7&index=1"),

    ("CS61A", "Homework 5", "Homework 5", "Reading", "Ch 2.9: Recursive Objects", "https://www.composingprograms.com/pages/29-recursive-objects.html"),
    ("CS61A", "Homework 5", "Homework 5", "Reading", "Ch 2.8: Efficiency", "https://www.composingprograms.com/pages/28-efficiency.html"),
    ("CS61A", "Homework 5", "Homework 5", "Reading", "Ch 3.1: Scheme Introduction", "https://www.composingprograms.com/pages/31-introduction.html"),
    ("CS61A", "Homework 5", "Homework 5", "Reading", "Ch 3.2: Functional Programming", "https://www.composingprograms.com/pages/32-functional-programming.html"),
    ("CS61A", "Homework 5", "Homework 5", "Video", "Lecture 16: Linked Lists", "https://www.youtube.com/watch?v=yC4WPw_6ehY&list=PLx38hZJ5RLZfpHYLasG2fsMHBFDWvdkBT&index=1"),
    ("CS61A", "Homework 5", "Homework 5", "Video", "Lecture 17: Efficiency", "https://www.youtube.com/watch?v=DWhsOSHjY98&list=PL6BsET-8jgYU9eOK2Ft8hQuzIWb4h-Tim"),
    ("CS61A", "Homework 5", "Homework 5", "Video", "Lecture 18: Scheme", "https://www.youtube.com/watch?v=esIvijecRFw&list=PL6BsET-8jgYWGDX7c-OKSMCh4QCBZ7Bs4"),

    ("CS61A", "Homework 6", "Homework 6", "Reading", "Ch 4.3: Declarative Programming", "https://www.composingprograms.com/pages/43-declarative-programming.html"),
    ("CS61A", "Homework 6", "Homework 6", "Video", "Lecture 22: SQL and Tables", "https://www.youtube.com/watch?v=lombSNkvRR4&list=PLx38hZJ5RLZesH9b4St6HNAH-NC0yOD00&index=1"),
    ("CS61A", "Homework 6", "Homework 6", "Video", "Lecture 23: Aggregation and Databases", "https://www.youtube.com/watch?v=2ajhv_e_u5Q&list=PLx38hZJ5RLZeSZJObFKl1993Q5cXMABL3&index=1"),

    ("CS61A", "Homework 7", "Homework 7", "Video", "Lecture 27: Final Review", "https://www.youtube.com/watch?v=_wfbb189nJA&list=PLx38hZJ5RLZf1a2bhgcoj_1Ifkn8tli0L&index=1"),

    # ── CS61A Projects ──────────────────────────────────────────────────────
    ("CS61A", "Hog Checkpoint", "Hog Checkpoint", "Video", "Hog Starting Videos", "https://www.youtube.com/watch?v=FQHZwBEYGSM&list=PLx38hZJ5RLZfpHDDcEnevQqlX4wTxuMAD&index=1"),

    ("CS61A", "Hog", "Hog", "Video", "Hog Starting Videos", "https://www.youtube.com/watch?v=FQHZwBEYGSM&list=PLx38hZJ5RLZfpHDDcEnevQqlX4wTxuMAD&index=1"),

    ("CS61A", "Cats Checkpoint", "Cats Checkpoint", "Video", "Cats Starting Videos", "https://www.youtube.com/watch?v=dq_cByFCRqY&list=PLx38hZJ5RLZe87guXM0aEm5VYwY6Mzbdy&index=1"),

    ("CS61A", "Cats", "Cats", "Video", "Cats Starting Videos", "https://www.youtube.com/watch?v=dq_cByFCRqY&list=PLx38hZJ5RLZe87guXM0aEm5VYwY6Mzbdy&index=1"),

    ("CS61A", "Ants Checkpoint", "Ants Checkpoint", "Video", "Ants Starting Videos", "https://www.youtube.com/watch?v=aJtR9HkE3NY&list=PLx38hZJ5RLZdH1AQFUuP-ixu7nAEK4OLP&index=1"),

    ("CS61A", "Ants", "Ants", "Video", "Ants Starting Videos", "https://www.youtube.com/watch?v=aJtR9HkE3NY&list=PLx38hZJ5RLZdH1AQFUuP-ixu7nAEK4OLP&index=1"),

    ("CS61A", "Scheme Checkpoint", "Scheme Checkpoint", "Video", "Lecture 18: Scheme", "https://www.youtube.com/watch?v=esIvijecRFw&list=PL6BsET-8jgYWGDX7c-OKSMCh4QCBZ7Bs4"),
    ("CS61A", "Scheme Checkpoint", "Scheme Checkpoint", "Video", "Lecture 19: Scheme Lists", "https://www.youtube.com/watch?v=M8nvWOAHLso&list=PL6BsET-8jgYW3h5HuWwcoTP4NTmLGB95p"),
    ("CS61A", "Scheme Checkpoint", "Scheme Checkpoint", "Video", "Lecture 20: Interpreters", "https://www.youtube.com/watch?v=bnUkFcTcUxM&list=PLx38hZJ5RLZeeyD43PD6M-wNmMg88IZXW&index=1"),
    ("CS61A", "Scheme Checkpoint", "Scheme Checkpoint", "Video", "Lecture 21: Tail Calls", "https://www.youtube.com/watch?v=zOxxB-gdO9U&list=PLx38hZJ5RLZdTRcbg-7Y59QARgHW4i3E8&index=1"),

    ("CS61A", "Scheme", "Scheme", "Video", "Lecture 18: Scheme", "https://www.youtube.com/watch?v=esIvijecRFw&list=PL6BsET-8jgYWGDX7c-OKSMCh4QCBZ7Bs4"),
    ("CS61A", "Scheme", "Scheme", "Video", "Lecture 19: Scheme Lists", "https://www.youtube.com/watch?v=M8nvWOAHLso&list=PL6BsET-8jgYW3h5HuWwcoTP4NTmLGB95p"),
    ("CS61A", "Scheme", "Scheme", "Video", "Lecture 20: Interpreters", "https://www.youtube.com/watch?v=bnUkFcTcUxM&list=PLx38hZJ5RLZeeyD43PD6M-wNmMg88IZXW&index=1"),
    ("CS61A", "Scheme", "Scheme", "Video", "Lecture 21: Tail Calls", "https://www.youtube.com/watch?v=zOxxB-gdO9U&list=PLx38hZJ5RLZdTRcbg-7Y59QARgHW4i3E8&index=1"),

    # ── CS61A Other ─────────────────────────────────────────────────────────
    ("CS61A", "Orientation Quiz (Optional)", "Orientation Quiz (Optional)", "Video", "Lecture 1: Welcome, Functions, Exceptions", "https://www.youtube.com/watch?v=gNv81_4X0uU&list=PL6BsET-8jgYULSxiV2garZ0FxbnXR08MP&index=1"),

    # ── CS10 Projects ───────────────────────────────────────────────────────
    ("CS10", "Project 1", "Project 1: Wordle™-lite", "Reading", "Proj 1 Walkthrough Slides", "https://drive.google.com/file/d/1liTxubkrh5-Vtp5CbQETI9BurAquIVSx/view"),
    ("CS10", "Project 2", "Project 2: Spelling Bee", "Reading", "Proj 2 Walkthrough Slides", "https://drive.google.com/file/d/1eJQpY5PpUwt3vesplElChY293NFQk4Vp/view"),
    ("CS10", "Project 3", "Project 3: 2048", "Reading", "Proj 3 Walkthrough Slides", "https://drive.google.com/file/d/1koa1TbOmoDa5tiIEm6hohQjiMaWjLI1H/view"),
    ("CS10", "Project 4", "Project 4: Tech in Context", "Reading", "Proj 4 Walkthrough Slides", "https://drive.google.com/drive/folders/1Rr0uR3vTD9ch5qs6IaLWrtEILqh_mCzk"),
    ("CS10", "Project 4", "Project 4: Presentations", "Reading", "Proj 4 Walkthrough Slides", "https://drive.google.com/drive/folders/1Rr0uR3vTD9ch5qs6IaLWrtEILqh_mCzk"),
    ("CS10", "Project 4", "Project 4: Feedback + Comments", "Reading", "Proj 4 Walkthrough Slides", "https://drive.google.com/drive/folders/1Rr0uR3vTD9ch5qs6IaLWrtEILqh_mCzk"),
    ("CS10", "Project 5", "Project 5: Proposals", "Reading", "Example bug writeup", "https://docs.google.com/document/d/1A6Tzm0UZte8gMnnmE2PV1J9xO__z6SaLkDVA6j3-I5s/edit?tab=t.0"),
    ("CS10", "Project 5", "Project 5: Proposal Meetings", "Reading", "Example bug writeup", "https://docs.google.com/document/d/1A6Tzm0UZte8gMnnmE2PV1J9xO__z6SaLkDVA6j3-I5s/edit?tab=t.0"),
    ("CS10", "Project 5", "Project 5: Final Project", "Reading", "Example bug writeup", "https://docs.google.com/document/d/1A6Tzm0UZte8gMnnmE2PV1J9xO__z6SaLkDVA6j3-I5s/edit?tab=t.0"),
]


def _doc_id(course_code: str, assignment_code: str, resource_name: str) -> str:
    """Stable document ID derived from the composite key."""
    raw = f"{course_code}__{assignment_code}__{resource_name}"
    return re.sub(r"[^\w]", "_", raw)


def build_documents() -> List[Dict[str, str]]:
    """Convert raw tuples into Firestore document dicts."""
    docs = []
    for course_code, assignment_code, assignment_name, resource_type, resource_name, link in RESOURCES:
        docs.append({
            "course_code": course_code,
            "assignment_code": assignment_code,
            "assignment_name": assignment_name,
            "resource_type": resource_type,
            "resource_name": resource_name,
            "link": link,
        })
    return docs


def delete_stale_cs61a_docs(db: firestore.Client, new_doc_ids: Set[str]) -> int:
    """Delete CS61A docs in Firestore whose IDs are not in the current RESOURCES list."""
    collection_ref = db.collection("assignment_resources")
    stale_docs = [
        doc for doc in collection_ref.where("course_code", "==", "CS61A").stream()
        if doc.id not in new_doc_ids
    ]
    for doc in stale_docs:
        d = doc.to_dict()
        print(f"   Deleting stale: {d.get('assignment_code')} / {d.get('resource_name') or '(no resource)'} [{doc.id}]")
        doc.reference.delete()
    return len(stale_docs)


def upload_resources(db: firestore.Client, documents: List[Dict[str, str]]) -> Dict[str, int]:
    """
    Upsert resources to Firestore using stable document IDs.

    Uses set(merge=True) so re-running updates changed fields (e.g. renamed
    assignment_name) rather than skipping existing entries.
    """
    stats = {"inserted": 0, "updated": 0, "errors": 0}
    collection_ref = db.collection("assignment_resources")

    for doc_data in documents:
        doc_id = _doc_id(
            doc_data["course_code"],
            doc_data["assignment_code"],
            doc_data.get("resource_name", ""),
        )
        doc_ref = collection_ref.document(doc_id)

        try:
            existing = doc_ref.get()
            if existing.exists:
                existing_data = existing.to_dict()
                changed = any(existing_data.get(k) != v for k, v in doc_data.items())
                if changed:
                    doc_ref.set(doc_data, merge=True)
                    stats["updated"] += 1
                    print(f"   Updated: {doc_data['course_code']} / {doc_data['assignment_code']} / {doc_data['resource_name'] or '(no resource)'}")
                else:
                    print(f"   No change: {doc_data['course_code']} / {doc_data['assignment_code']} / {doc_data['resource_name'] or '(no resource)'}")
            else:
                doc_ref.set(doc_data)
                stats["inserted"] += 1
                print(f"   Inserted: {doc_data['course_code']} / {doc_data['assignment_code']} / {doc_data['resource_name'] or '(no resource)'}")
        except Exception as e:
            stats["errors"] += 1
            print(f"   Error ({doc_data['assignment_code']}): {e}")

    return stats


def main():
    print("=" * 60)
    print("Uploading Assignment Resources to Firestore")
    print("=" * 60)

    print("\nConnecting to Firestore...")
    try:
        db = init_firestore()
        print(f"Connected to project: {settings.FIREBASE_PROJECT_ID}")
    except Exception as e:
        print(f"Error connecting to Firestore: {e}")
        return

    documents = build_documents()
    new_doc_ids = {
        _doc_id(d["course_code"], d["assignment_code"], d.get("resource_name", ""))
        for d in documents
    }

    print(f"\nPrepared {len(documents)} resource entries\n")

    print("--- Cleaning up stale CS61A docs ---")
    deleted = delete_stale_cs61a_docs(db, new_doc_ids)
    print(f"   Deleted {deleted} stale doc(s)\n")

    print("--- Uploading resources ---")
    stats = upload_resources(db, documents)

    print(f"\nDone! Inserted: {stats['inserted']}, Updated: {stats['updated']}, Errors: {stats['errors']}")
    print("=" * 60)


if __name__ == "__main__":
    main()
