"""
Upload assignment resources to Firestore.

Uploads each row to the 'assignment_resources' collection using a stable
document ID derived from (course_code, assignment_code, resource_name) so
re-running always updates existing entries (e.g. assignment_name renames)
rather than silently skipping them.

Also deletes stale CS61A docs whose IDs are no longer generated by this script,
keeping Firestore in sync with the RESOURCES list below.
"""

import re
import sys
from pathlib import Path
from typing import Dict, List, Set

import firebase_admin
from firebase_admin import credentials, firestore

SERVICES_DIR = Path(__file__).resolve().parent.parent
if str(SERVICES_DIR) not in sys.path:
    sys.path.append(str(SERVICES_DIR))

from shared import settings


def init_firestore() -> firestore.Client:
    """Initialize Firebase Admin SDK and return a Firestore client."""
    if not firebase_admin._apps:
        sa_path = str(settings.FIREBASE_SERVICE_ACCOUNT_PATH)
        cred = credentials.Certificate(sa_path)
        firebase_admin.initialize_app(cred, {
            "projectId": settings.FIREBASE_PROJECT_ID,
        })
    return firestore.client()


# Fields: (course_code, assignment_code, assignment_name, resource_type, resource_name, link)
#
# assignment_code and assignment_name must exactly match the Gradescope assignment name.
# These names drive both the deadline matching (submission check) and the resource lookup.
RESOURCES = [
    # ── CS61A ───────────────────────────────────────────────────────────────
    ("CS61A", "Lab 0", "Lab 0", "Link", "Assignment Link", "https://cs61a.org/lab/lab00/"),
    ("CS61A", "Lab 0", "Lab 0", "Reading", "Reading: Ch 1.1: Getting Started", "https://www.composingprograms.com/pages/11-getting-started.html"),

    ("CS61A", "Lab 1", "Lab 1", "Link", "Assignment Link", "https://cs61a.org/lab/lab01/"),
    ("CS61A", "Lab 1", "Lab 1", "Reading", "Reading: 1.2 – 1.5", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 1", "Lab 1", "Video", "Videos: Functions, Control", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Orientation Quiz (Optional)", "Orientation Quiz (Optional)", "Link", "Assignment Link", "https://us.prairietest.com/"),
    ("CS61A", "Orientation Quiz (Optional)", "Orientation Quiz (Optional)", "Video", "Lecture 1: Welcome, Functions, Exceptions", "https://www.youtube.com/watch?v=gNv81_4X0uU&list=PL6BsET-8jgYULSxiV2garZ0FxbnXR08MP&index=1"),

    ("CS61A", "Lab 2", "Lab 2", "Link", "Assignment Link", "https://cs61a.org/lab/lab02/"),
    ("CS61A", "Lab 2", "Lab 2", "Reading", "Reading: 1.6", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 2", "Lab 2", "Video", "Videos: Higher Order Functions, Environments", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Homework 1", "Homework 1", "Link", "Assignment Link", "https://cs61a.org/hw/hw01/"),
    ("CS61A", "Homework 1", "Homework 1", "Reading", "Reading: 1.2 – 1.6", "https://www.composingprograms.com/"),
    ("CS61A", "Homework 1", "Homework 1", "Video", "Videos: Functions, Control, Higher Order Functions", "https://www.askademia.org/cs61a/su26/playlists/functions"),

    ("CS61A", "Lab 3", "Lab 3", "Link", "Assignment Link", "https://cs61a.org/lab/lab03/"),
    ("CS61A", "Lab 3", "Lab 3", "Reading", "Reading: 1.7", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 3", "Lab 3", "Video", "Videos: Recursion, Tree Recursion", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Hog Checkpoint", "Hog Checkpoint", "Link", "Assignment Link", "https://cs61a.org/proj/hog/"),
    ("CS61A", "Hog Checkpoint", "Hog Checkpoint", "Video", "Hog Starting Videos", "https://www.youtube.com/playlist?list=PLx38hZJ5RLZf9k0xEv1fD5FmR0-gjb9BM"),

    ("CS61A", "Hog", "Hog", "Video", "Hog Starting Videos", "https://www.youtube.com/playlist?list=PLx38hZJ5RLZf9k0xEv1fD5FmR0-gjb9BM"),

    ("CS61A", "Lab 4", "Lab 4", "Link", "Assignment Link", "https://cs61a.org/lab/lab04/"),
    ("CS61A", "Lab 4", "Lab 4", "Reading", "Reading: 2.3", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 4", "Lab 4", "Video", "Videos: Sequences and Containers, Trees", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Homework 2", "Homework 2", "Link", "Assignment Link", "https://cs61a.org/hw/hw02/"),
    ("CS61A", "Homework 2", "Homework 2", "Reading", "Reading: 1.7, 2.3", "https://www.composingprograms.com/"),
    ("CS61A", "Homework 2", "Homework 2", "Video", "Videos: Recursion, Tree Recursion, Sequences, Containers", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Lab 5", "Lab 5", "Link", "Assignment Link", "https://cs61a.org/lab/lab05/"),
    ("CS61A", "Lab 5", "Lab 5", "Reading", "Reading: 2.2, 2.4, 4.2", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 5", "Lab 5", "Video", "Videos: Mutability, Data Abstraction, Iterators, Generators", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Cats Checkpoint", "Cats Checkpoint", "Link", "Assignment Link", "https://cs61a.org/proj/cats/"),
    ("CS61A", "Cats Checkpoint", "Cats Checkpoint", "Video", "Cats Starting Videos", "https://www.youtube.com/watch?v=dq_cByFCRqY&list=PLx38hZJ5RLZe87guXM0aEm5VYwY6Mzbdy&index=1"),

    ("CS61A", "Homework 3", "Homework 3", "Link", "Assignment Link", "https://cs61a.org/hw/hw03/"),
    ("CS61A", "Homework 3", "Homework 3", "Reading", "Reading: 2.2 – 2.4, 4.2", "https://www.composingprograms.com/"),
    ("CS61A", "Homework 3", "Homework 3", "Video", "Videos: Mutability, Data Abstraction, Trees, Iterators, Generators", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Lab 6", "Lab 6", "Link", "Assignment Link", "https://cs61a.org/lab/lab06/"),
    ("CS61A", "Lab 6", "Lab 6", "Reading", "Reading: 2.5, 2.7", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 6", "Lab 6", "Video", "Videos: Objects, Attributes, Inheritance, Representation", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Cats", "Cats", "Video", "Cats Starting Videos", "https://www.youtube.com/watch?v=dq_cByFCRqY&list=PLx38hZJ5RLZe87guXM0aEm5VYwY6Mzbdy&index=1"),

    ("CS61A", "Lab 7", "Lab 7", "Link", "Assignment Link", "https://cs61a.org/lab/lab07/"),
    ("CS61A", "Lab 7", "Lab 7", "Reading", "Reading: 2.7, 2.9", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 7", "Lab 7", "Video", "Videos: Inheritance, Representation, Tree Class, Tree Mutation", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Homework 4", "Homework 4", "Link", "Assignment Link", "https://cs61a.org/hw/hw04/"),
    ("CS61A", "Homework 4", "Homework 4", "Reading", "Reading: 2.5, 2.7, 2.9", "https://www.composingprograms.com/"),
    ("CS61A", "Homework 4", "Homework 4", "Video", "Videos: Objects, Attributes, Inheritance, String Representation, Tree Class, Tree Mutation", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Lab 8", "Lab 8", "Link", "Assignment Link", "https://cs61a.org/lab/lab08/"),
    ("CS61A", "Lab 8", "Lab 8", "Reading", "Reading: 2.9", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 8", "Lab 8", "Video", "Videos: Linked Lists", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Ants Checkpoint", "Ants Checkpoint", "Link", "Assignment Link", "https://cs61a.org/proj/ants/"),
    ("CS61A", "Ants Checkpoint", "Ants Checkpoint", "Video", "Ants Starting Videos", "https://www.youtube.com/watch?v=aJtR9HkE3NY&list=PLx38hZJ5RLZdH1AQFUuP-ixu7nAEK4OLP&index=1"),

    ("CS61A", "Lab 9", "Lab 9", "Link", "Assignment Link", "https://cs61a.org/lab/lab09/"),
    ("CS61A", "Lab 9", "Lab 9", "Reading", "Reading: 3.1 – 3.2", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 9", "Lab 9", "Video", "Videos: Scheme and Scheme Lists", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Ants", "Ants", "Video", "Ants Starting Videos", "https://www.youtube.com/watch?v=aJtR9HkE3NY&list=PLx38hZJ5RLZdH1AQFUuP-ixu7nAEK4OLP&index=1"),

    ("CS61A", "Homework 5", "Homework 5", "Link", "Assignment Link", "https://cs61a.org/hw/hw05/"),
    ("CS61A", "Homework 5", "Homework 5", "Reading", "Reading: 2.8 – 3.2", "https://www.composingprograms.com/"),
    ("CS61A", "Homework 5", "Homework 5", "Video", "Videos: Linked Lists, Efficiency, Scheme", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Lab 10", "Lab 10", "Link", "Assignment Link", "https://cs61a.org/lab/lab10/"),
    ("CS61A", "Lab 10", "Lab 10", "Reading", "Reading: 3.4 – 3.5", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 10", "Lab 10", "Video", "Videos: Interpreters, Tail Recursion, Tail Calls, Map and Reduce", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Lab 11", "Lab 11", "Link", "Assignment Link", "https://cs61a.org/lab/lab11/"),
    ("CS61A", "Lab 11", "Lab 11", "Reading", "Reading: 4.3", "https://www.composingprograms.com/"),
    ("CS61A", "Lab 11", "Lab 11", "Video", "Videos: SQL, Tables, Aggregation, Databases", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Homework 6", "Homework 6", "Link", "Assignment Link", "https://cs61a.org/hw/hw06/"),
    ("CS61A", "Homework 6", "Homework 6", "Reading", "Reading: 4.3", "https://www.composingprograms.com/"),
    ("CS61A", "Homework 6", "Homework 6", "Video", "Videos: SQL, Tables, Aggregation, Databases", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Scheme Checkpoint", "Scheme Checkpoint", "Video", "Videos: Scheme, Scheme Lists, Interpreters, Tail Recursion, Tail Calls, Map and Reduce", "https://www.askademia.org/cs61a/su26/cs61a-su26-upload-1775199158"),

    ("CS61A", "Lab 12", "Lab 12", "Video", "Lecture 27: Final Review", "https://www.youtube.com/watch?v=_wfbb189nJA&list=PLx38hZJ5RLZf1a2bhgcoj_1Ifkn8tli0L&index=1"),

    ("CS61A", "Homework 7", "Homework 7", "Video", "Lecture 27: Final Review", "https://www.youtube.com/watch?v=_wfbb189nJA&list=PLx38hZJ5RLZf1a2bhgcoj_1Ifkn8tli0L&index=1"),

    ("CS61A", "Scheme", "Scheme", "Video", "Videos: Scheme, Scheme Lists, Interpreters, Tail Calls", "https://www.askademia.org/cs61a/su26/playlists/functions"),

    # ── CS10 Projects ───────────────────────────────────────────────────────
    ("CS10", "Project 1", "Project 1: Wordle™-lite", "Reading", "Proj 1 Walkthrough Slides", "https://drive.google.com/file/d/1liTxubkrh5-Vtp5CbQETI9BurAquIVSx/view"),
    ("CS10", "Project 2", "Project 2: Spelling Bee", "Reading", "Proj 2 Walkthrough Slides", "https://drive.google.com/file/d/1eJQpY5PpUwt3vesplElChY293NFQk4Vp/view"),
    ("CS10", "Project 3", "Project 3: 2048", "Reading", "Proj 3 Walkthrough Slides", "https://drive.google.com/file/d/1koa1TbOmoDa5tiIEm6hohQjiMaWjLI1H/view"),
    ("CS10", "Project 4", "Project 4: Tech in Context", "Reading", "Proj 4 Walkthrough Slides", "https://drive.google.com/drive/folders/1Rr0uR3vTD9ch5qs6IaLWrtEILqh_mCzk"),
    ("CS10", "Project 4", "Project 4: Presentations", "Reading", "Proj 4 Walkthrough Slides", "https://drive.google.com/drive/folders/1Rr0uR3vTD9ch5qs6IaLWrtEILqh_mCzk"),
    ("CS10", "Project 4", "Project 4: Feedback + Comments", "Reading", "Proj 4 Walkthrough Slides", "https://drive.google.com/drive/folders/1Rr0uR3vTD9ch5qs6IaLWrtEILqh_mCzk"),
    ("CS10", "Project 5", "Project 5: Proposals", "Reading", "Example bug writeup", "https://docs.google.com/document/d/1A6Tzm0UZte8gMnnmE2PV1J9xO__z6SaLkDVA6j3-I5s/edit?tab=t.0"),
    ("CS10", "Project 5", "Project 5: Proposal Meetings", "Reading", "Example bug writeup", "https://docs.google.com/document/d/1A6Tzm0UZte8gMnnmE2PV1J9xO__z6SaLkDVA6j3-I5s/edit?tab=t.0"),
    ("CS10", "Project 5", "Project 5: Final Project", "Reading", "Example bug writeup", "https://docs.google.com/document/d/1A6Tzm0UZte8gMnnmE2PV1J9xO__z6SaLkDVA6j3-I5s/edit?tab=t.0"),
]


def _doc_id(course_code: str, assignment_code: str, resource_name: str) -> str:
    """Stable document ID derived from the composite key."""
    raw = f"{course_code}__{assignment_code}__{resource_name}"
    return re.sub(r"[^\w]", "_", raw)


def build_documents() -> List[Dict[str, str]]:
    """Convert raw tuples into Firestore document dicts."""
    docs = []
    for course_code, assignment_code, assignment_name, resource_type, resource_name, link in RESOURCES:
        docs.append({
            "course_code": course_code,
            "assignment_code": assignment_code,
            "assignment_name": assignment_name,
            "resource_type": resource_type,
            "resource_name": resource_name,
            "link": link,
        })
    return docs


def delete_stale_cs61a_docs(db: firestore.Client, new_doc_ids: Set[str]) -> int:
    """Delete CS61A docs in Firestore whose IDs are not in the current RESOURCES list."""
    collection_ref = db.collection("assignment_resources")
    stale_docs = [
        doc for doc in collection_ref.where("course_code", "==", "CS61A").stream()
        if doc.id not in new_doc_ids
    ]
    for doc in stale_docs:
        d = doc.to_dict()
        print(f"   Deleting stale: {d.get('assignment_code')} / {d.get('resource_name') or '(no resource)'} [{doc.id}]")
        doc.reference.delete()
    return len(stale_docs)


def upload_resources(db: firestore.Client, documents: List[Dict[str, str]]) -> Dict[str, int]:
    """
    Upsert resources to Firestore using stable document IDs.

    Uses set(merge=True) so re-running updates changed fields (e.g. renamed
    assignment_name) rather than skipping existing entries.
    """
    stats = {"inserted": 0, "updated": 0, "errors": 0}
    collection_ref = db.collection("assignment_resources")

    for doc_data in documents:
        doc_id = _doc_id(
            doc_data["course_code"],
            doc_data["assignment_code"],
            doc_data.get("resource_name", ""),
        )
        doc_ref = collection_ref.document(doc_id)

        try:
            existing = doc_ref.get()
            if existing.exists:
                existing_data = existing.to_dict()
                changed = any(existing_data.get(k) != v for k, v in doc_data.items())
                if changed:
                    doc_ref.set(doc_data, merge=True)
                    stats["updated"] += 1
                    print(f"   Updated: {doc_data['course_code']} / {doc_data['assignment_code']} / {doc_data['resource_name'] or '(no resource)'}")
                else:
                    print(f"   No change: {doc_data['course_code']} / {doc_data['assignment_code']} / {doc_data['resource_name'] or '(no resource)'}")
            else:
                doc_ref.set(doc_data)
                stats["inserted"] += 1
                print(f"   Inserted: {doc_data['course_code']} / {doc_data['assignment_code']} / {doc_data['resource_name'] or '(no resource)'}")
        except Exception as e:
            stats["errors"] += 1
            print(f"   Error ({doc_data['assignment_code']}): {e}")

    return stats


def main():
    print("=" * 60)
    print("Uploading Assignment Resources to Firestore")
    print("=" * 60)

    print("\nConnecting to Firestore...")
    try:
        db = init_firestore()
        print(f"Connected to project: {settings.FIREBASE_PROJECT_ID}")
    except Exception as e:
        print(f"Error connecting to Firestore: {e}")
        return

    documents = build_documents()
    new_doc_ids = {
        _doc_id(d["course_code"], d["assignment_code"], d.get("resource_name", ""))
        for d in documents
    }

    print(f"\nPrepared {len(documents)} resource entries\n")

    print("--- Cleaning up stale CS61A docs ---")
    deleted = delete_stale_cs61a_docs(db, new_doc_ids)
    print(f"   Deleted {deleted} stale doc(s)\n")

    print("--- Uploading resources ---")
    stats = upload_resources(db, documents)

    print(f"\nDone! Inserted: {stats['inserted']}, Updated: {stats['updated']}, Errors: {stats['errors']}")
    print("=" * 60)


if __name__ == "__main__":
    main()
